basePath: /api/v1
definitions:
  response.CustomerListResponse:
    properties:
      limit:
        type: integer
      offset:
        type: integer
      rows:
        items:
          $ref: '#/definitions/response.CustomerResponse'
        type: array
      total:
        type: integer
    type: object
  response.CustomerResponse:
    properties:
      id:
        type: integer
      phone:
        type: string
      phone_valid:
        type: boolean
    type: object
  response.Error:
    properties:
      message:
        type: string
    type: object
info:
  contact: {}
  description: phone list API example
  title: phone list API
  version: "1.0"
paths:
  /customers:
    get:
      parameters:
      - description: pagination limit
        in: query
        name: limit
        type: integer
      - description: pagination offset
        in: query
        name: offset
        type: integer
      - description: phone country
        enum:
        - cameroon
        - ethiopia
        - morocco
        - mozambique
        - uganda
        in: query
        name: country
        type: string
      - description: phone state
        enum:
        - 1
        - 2
        in: query
        name: state
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/response.CustomerListResponse'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.Error'
      tags:
      - customers
swagger: "2.0"
